spring.datasource.url=jdbc:postgresql://localhost:5432/securevault
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.encryption.key=q7Yx3Kp9Vn2Lm8Rz4Tq6Wc1Hs5Jf0Dg8P2aN7mXk9Qs=
app.jwt.secret=WyPq+TXq+7OBu/+Wf/XIb5hi+YrHF5pOP7/v93Maj7I=